package com.wine.bottle.util;

/**
 * Region viticole
 */
public enum WineLocation {
	ALSACE, OTHER, BEAUJOLAIS, BORDELAIS, BOURGOGNE, CHAMPAGNE, COGNAC, CORSE, JURA, BUGEY, SAVOIE,
	LANGUEDOC_ROUSSILLON, PROVENCE, SUD_OUEST, LOIRE, RHONE
}
