## PostgreSQL
spring.datasource.url=jdbc:postgresql://ccaml3dimis7eh.cluster-czz5s0kz4scl.eu-west-1.rds.amazonaws.com:5432/d5lnu5pk2g45h1
spring.datasource.username=u48cs3m263eo9m
spring.datasource.password=pb4793fb1a2807fe85c261454c9af99d88a149464adac516647bd04724a1b77a4